[package]
name = "foo"
version = "0.1.0"
authors = ["Eyal Kalderon <ebkalderon@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.32"
blake3 = "0.3.6"
filetime = "0.2.12"
hex = { version = "0.4.2", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.58"
smol_str = { version = "0.1.17", features = ["serde"] }
tempfile = "3.1.0"
